theme: jekyll-theme-hacker
title: Ronnie Sunde
description: Blog
google_analytics: sdfgkj
# jekyll-theme-architect

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
